local RSGCore = exports['rsg-core']:GetCoreObject()
local config = require 'shared.config'

local function notify(src, text, notifType)
    TriggerClientEvent('ox_lib:notify', src, { title = text, type = notifType or 'error', duration = 5000 })
end

local function isBlocked(ply)
    local meta = ply.PlayerData.metadata
    return meta.isdead or meta.inlaststand or meta.ishandcuffed
end

local function giveItem(target, itemData, amount, info, reason)
    local success = Inventory.AddItem(target, itemData.name, amount, false, info, reason)
    if success then
        TriggerClientEvent('rsg-inventory:client:ItemBox', target, itemData, 'add', amount)
        if Player(target).state.inv_busy then
            TriggerClientEvent('rsg-inventory:client:updateInventory', target)
        end
    end
    return success
end

-- /giveitem [id] [item] [amount]
lib.addCommand(config.CommandNames.GiveItem, {
    help = locale('info.giveitem_help'),
    restricted = 'group.admin',
    params = {
        { name = 'target', type = 'playerId', help = locale('info.param_target') },
        { name = 'item', type = 'string', help = locale('info.param_item') },
        { name = 'amount', type = 'number', help = locale('info.param_amount'), optional = true },
    }
}, function(source, args)
    local player = RSGCore.Functions.GetPlayer(args.target)
    if not player then return notify(source, locale('error.pdne')) end

    local itemData = RSGCore.Shared.Items[tostring(args.item):lower()]
    if not itemData then return notify(source, locale('error.idne')) end

    local amount = math.floor(tonumber(args.amount) or 1)
    if amount < 1 then return notify(source, locale('error.invalid_amount')) end

    local info = {}
    if itemData.name == 'id_card' then
        local char = player.PlayerData.charinfo
        info = {
            citizenid = player.PlayerData.citizenid,
            firstname = char.firstname,
            lastname = char.lastname,
            birthdate = char.birthdate,
            gender = char.gender,
            nationality = char.nationality,
        }
    elseif itemData.type == 'weapon' or itemData.unique then
        amount = 1 -- serial/quality are generated by AddItem
    end

    if giveItem(args.target, itemData, amount, info, 'give item command') then
        notify(source, locale('info.yhg', itemData.label, amount), 'success')
    else
        notify(source, locale('error.cgitem'))
    end
end)

-- /randomitems
lib.addCommand(config.CommandNames.RandomItems, {
    help = locale('info.randomitems_help'),
    restricted = 'group.god'
}, function(source)
    if not RSGCore.Functions.GetPlayer(source) then return end

    local pool = {}
    for _, v in pairs(RSGCore.Shared.Items) do
        if v.type ~= 'weapon' then pool[#pool + 1] = v end
    end
    if #pool == 0 then return end

    for _ = 1, 10 do
        local item = pool[math.random(#pool)]
        if not giveItem(source, item, item.unique and 1 or math.random(1, 10), nil, 'random items command') then break end
        Wait(1000)
    end
end)

-- /clearinv [id]
lib.addCommand(config.CommandNames.ClearInv, {
    help = locale('info.clearinv_help'),
    restricted = 'group.admin',
    params = {
        { name = 'target', type = 'playerId', help = locale('info.param_target'), optional = true }
    }
}, function(source, args)
    local target = args.target or source
    if not RSGCore.Functions.GetPlayer(target) then return notify(source, locale('error.pdne')) end
    Inventory.ClearInventory(target)
    notify(target, locale('info.inventory_cleared'), 'success')
    if target ~= source then
        notify(source, locale('info.inventory_cleared_for') .. GetPlayerName(target), 'success')
    end
end)

-- /closeinv
RegisterCommand(config.CommandNames.CloseInv, function(source)
    if source <= 0 then return end
    Inventory.CloseInventory(source, OpenedInventories[source])
end, false)

-- Hotbar (triggered by the client keybind/command)
RegisterCommand('serversidehotbar', function(source)
    if source <= 0 or Player(source).state.inv_busy then return end
    local ply = RSGCore.Functions.GetPlayer(source)
    if not ply or isBlocked(ply) then return end

    local hotbarItems = {}
    for i = 1, 5 do
        hotbarItems[i] = ply.PlayerData.items[i]
    end
    TriggerClientEvent('rsg-inventory:client:hotbar', source, hotbarItems)
end, false)

-- /inventory
RegisterCommand(config.CommandNames.Inventory, function(source)
    if source <= 0 or Player(source).state.inv_busy then return end
    local ply = RSGCore.Functions.GetPlayer(source)
    if not ply or isBlocked(ply) then return end
    Inventory.OpenInventory(source)
end, false)
